trigger:
- main

pool:
  name: self-hosted

stages:
- stage: Prepare
  jobs:
  - job: Prepare
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

- stage: Build
  jobs:
  - job: Build
    steps:
    - script: |
        
        cd client
        "C:\Program Files\nodejs\npm" install
        "C:\Program Files\nodejs\npm" install
      displayName: 'Build React App'

    - script: |
        SET PATH=%PATH%;C:\Program Files\nodejs\
        cd server
        "C:\Program Files\nodejs\npm" install
      displayName: 'Install Dependencies for Express Server'

- stage: Test
  jobs:
  - job: Test
    steps:
    - script: |
        cd client
        npm test -- --coverage
      displayName: 'Test React App'

    - script: |
        cd server
        npm test -- --coverage
      displayName: 'Test Express Server'
