trigger:
- main

pool:
  name: self-hosted-centennial

stages:
- stage: Prepare
  jobs:
  - job: Prepare
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

- stage: Build
  jobs:
  - job: Build
    steps:
    - script: |
        cd client
        npm install
        npm run build
      displayName: 'Build React App'

    - script: |
        cd server
        npm install
      displayName: 'Install Dependencies for Express Server'

- stage: Test
  jobs:
  - job: Test
    steps:
    - script: |
        cd server
        npm install
        npm test -- --coverage
      displayName: 'Test Application'